# Generated by Django 3.0.8 on 2020-07-27 18:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Mobile Phones', 'Mobile Phones'), ('Mobile Phone Accessories', 'Mobile Phone Accessories'), ('Computer Accessories', 'Computer Accessories'), ('TVs', 'TVs'), ('TV & Video Accessories', 'TV & Video Accessories'), ('Cameras & Camcorders', 'Cameras & Camcorders'), ('Audio & MP3', 'Audio & MP3'), ('Other Electronics', 'Other Electronics')], max_length=200, null=True)),
                ('location', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Upper West', 'Upper West'), ('Upper East', 'Upper East'), ('North East', 'North East'), ('Northen', 'Northen'), ('Savannah', 'Savannah'), ('Bono East', 'Bono East'), ('Brong Ahafo', 'Brong Ahafo'), ('Oti', 'Oti'), ('Ahafo', 'Ahafo'), ('Ashanti', 'Ashanti'), ('Volta', 'Volta'), ('Greater Accra', 'Greater Accra'), ('Western North', 'Western North'), ('Western', 'Western'), ('Eastern', 'Eastern'), ('Central', 'Central')], max_length=200, null=True)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('description', models.TextField()),
                ('published', models.BooleanField(default=False, null=True)),
                ('used', models.BooleanField(default=False, null=True)),
                ('negotiable', models.BooleanField(default=False, null=True)),
                ('main_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('date_posted', models.DateField(blank=True, default=datetime.datetime.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.Seller')),
            ],
        ),
    ]
